backend:
  name: git-gateway
  branch: main # Change to your production branch

local_backend: true # Enables Netlify CMS locally

publish_mode: editorial_workflow # Adds more options to content management

media_folder: static/imgages/uploads
public_folder: /imgages/uploads

collections:
  - label: "Blog"
    name: "blog"
    folder: "_posts/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
